lib/nimble_school_web/router.ex
defmodule NimbleSchoolWeb.Router do
  use NimbleSchoolWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NimbleSchoolWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/blog", BlogController, :index
    get "/blog/:id", BlogController, :show
    get "/blog/by/:tag", BlogController, :taglist
    get "/faq", BlogController, :faqindex
    get "/faq/:id", BlogController, :faqshow
  end

  # Other scopes may use custom stacks.
  # scope "/api", NimbleSchoolWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: NimbleSchoolWeb.Telemetry
    end
  end
end

lib/nimble_school/application.ex
defmodule NimbleSchool.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Telemetry supervisor
      NimbleSchoolWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: NimbleSchool.PubSub},
      # Start the Endpoint (http/https)
      NimbleSchoolWeb.Endpoint
      # Start a worker by calling: NimbleSchool.Worker.start_link(arg)
      # {NimbleSchool.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: NimbleSchool.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    NimbleSchoolWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/nimble_school/blog/blog.ex
defmodule NimbleSchool.Blog do
  alias NimbleSchool.Blog.Post
  use NimblePublisher,
    build: Post,
    from: Application.app_dir(:nimble_school, "priv/posts/**/*.md"),
    as: :posts,
    highlighters: [:makeup_elixir, :makeup_erlang]
  @posts Enum.sort_by(@posts, & &1.date, {:desc, Date})
  @tags @posts |> Enum.flat_map(& &1.tags) |> Enum.uniq() |> Enum.sort()
  def all_posts, do: @posts
  def all_tags, do: @tags

  def recent_posts(num \\ 5), do: Enum.take(all_posts(), num)

  defmodule NotFoundError, do: defexception [:message, plug_status: 404]
  def get_post_by_id!(id) do
    Enum.find(all_posts(), &(&1.id == id)) ||
    raise NotFoundError, "post with id=#{id} not found"
  end

  def get_posts_by_tag!(tag) do
    case Enum.filter(all_posts(), &(tag in &1.tags)) do
      [] -> raise NotFoundError, "post with tag=#{tag} not found"
      posts -> posts
    end
  end
end

lib/nimble_school/blog/post.ex
defmodule NimbleSchool.Blog.Post do
  @enforce_keys [:id, :author, :title, :body, :description, :tags, :date]
  defstruct [:id, :author, :title, :body, :description, :tags, :date]

  def build(filename, attrs, body) do
    [year, month_day_id] = filename |> Path.rootname() |> Path.split() |> Enum.take(-2)
    [month, day, id] = String.split(month_day_id, "-", parts: 3)
    date = Date.from_iso8601!("#{year}-#{month}-#{day}")
    struct!(__MODULE__, [id: id, date: date, body: body] ++ Map.to_list(attrs))
  end

end

lib/nimble_school/faqs/faq.ex
defmodule NimbleSchool.Faqs.Faq do
  @enforce_keys [:id, :question, :answer]
  defstruct [:id, :question, :answer]

  def build(filename, attrs, body) do
    [id] = filename |> Path.rootname() |> Path.split |> Enum.take(-1)
    struct!(__MODULE__, [id: id, answer: body] ++ Map.to_list(attrs))
  end
end

lib/nimble_school/faqs/faqs.ex
defmodule NimbleSchool.Faqs do
alias NimbleSchool.Faqs.Faq
  use NimblePublisher,
    build: Faq,
    from: Application.app_dir(:nimble_school, "priv/faqs/*.md"),
    as: :faqs

  @faqs Enum.sort_by(@faqs, & &1.question)

  def all_faqs, do: @faqs

  def get_post_by_id!(id) do
    Enum.find(all_faqs(), &(&1.id == id)) ||
    raise NotFoundError, "post with id=#{id} not found"
  end
end

lib/nimble_school_web/controllers/blog_controller.ex
defmodule NimbleSchoolWeb.BlogController do
  use NimbleSchoolWeb, :controller
  alias NimbleSchool.Blog
  alias NimbleSchool.Faqs

  def index(conn, _params) do
    render(conn, "index.html", posts: Blog.all_posts(), tags: Blog.all_tags(), newposts: Blog.recent_posts())
  end

  def show(conn, %{"id" => id}) do
    render(conn, "show.html", post: Blog.get_post_by_id!(id))
  end

  def taglist(conn, %{"tag" => tag}) do
    render(conn, "taglist.html", posts: Blog.get_posts_by_tag!(tag), tag: tag)
  end

  def faqindex(conn, _params) do
    render(conn, "faqindex.html", posts: Faqs.all_faqs())
  end

  def faqshow(conn, %{"id" => id}) do
    render(conn, "faqshow.html", post: Faqs.get_post_by_id!(id))
  end
end

lib/nimble_school_web/controllers/page_controller.ex
defmodule NimbleSchoolWeb.PageController do
  use NimbleSchoolWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/nimble_school_web/views/blog_view.ex
defmodule NimbleSchoolWeb.BlogView do
  use NimbleSchoolWeb, :view
end

lib/nimble_school_web/views/error_view.ex
defmodule NimbleSchoolWeb.ErrorView do
  use NimbleSchoolWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/nimble_school_web/views/layout_view.ex
defmodule NimbleSchoolWeb.LayoutView do
  use NimbleSchoolWeb, :view
end

lib/nimble_school_web/views/page_view.ex
defmodule NimbleSchoolWeb.PageView do
  use NimbleSchoolWeb, :view
end

lib/nimble_school_web/templates/blog/faqindex.html.eex
<h1>FAQ</h1>

<%= for post <- @posts do %>
    <div id="<%= post.id %>" style="mergin-bottom:3rem;">
        <h2>
            Question : <%= link post.question, to: Routes.blog_path(@conn, :faqshow, post)%>
        </h2>
    </div>
<% end %>
<br>
<%= link "← All posts", to: Routes.blog_path(@conn, :index) %>

lib/nimble_school_web/templates/blog/faqshow.html.eex
<%= link "← All FAQ", to: Routes.blog_path(@conn, :faqindex) %>
<h1><%= @post.question %></h1>
<%= raw @post.answer %>

lib/nimble_school_web/templates/blog/index.html.eex
<div id="section">
<h1>New posts</h1>
<%= for post <- @newposts do %>
    <div id="<%= post.id %>" style="mergin-bottom:3rem;">
        <h2>
            <%= link post.title, to: Routes.blog_path(@conn, :show, post)%>
        </h2>
        <p>
            <time><%= post.date %></time> by <%= post.author %>
        </p>
        <p>
            Tagged as <%= Enum.join(post.tags, ", ") %>
        </p>
        <%= raw post.description%>
    </div>
<% end %>

<hr>

<h1>Listing all posts</h1>
<%= for post <- @posts do %>
    <div id="<%= post.id %>" style="mergin-bottom: 3rem;">
        <h2>
            <%= link post.title, to: Routes.blog_path(@conn, :show, post)%>
        </h2>
        <p>
            <time><%= post.date %></time> by <%= post.author %>
        </p>
        <p>
            Tagged as <%= Enum.join(post.tags, ", ") %>
        </p>
        <%= raw post.description %>
    </div>
<% end %>

<hr>
<h1>Sarch for tags</h1>
<%= for tag <- @tags do %>
    <p>
    <%= link tag, to: Routes.blog_path(@conn, :taglist, tag)%>
    </p>
<% end %>

<hr>
<h1>FAQ</h1>
<%= link "FAQ", to: Routes.blog_path(@conn, :faqindex) %>

</div>

lib/nimble_school_web/templates/blog/show.html.eex
<%= link "← All posts", to: Routes.blog_path(@conn, :index) %>
<h1><%= @post.title %></h1>
<p>
    <time><%= @post.date %></time> by <%= @post.author %>
</p>
<p>
    Tagged as <%= Enum.join(@post.tags, ", ") %>
</p>
<%= raw @post.body %>

lib/nimble_school_web/templates/blog/taglist.html.eex
<h1>Tag：<%= @tag %></h1>

<%= for post <- @posts do %>
    <div id="<%= post.id %>" style="mergin-bottom: 3rem;">
        <h2>
            <%= link post.title, to: Routes.blog_path(@conn, :show, post)%>
        </h2>
        <p>
            <time><%= post.date %></time> by <%= post.author %>
        </p>
        <p>
            Tagged as <%= Enum.join(post.tags, ", ") %>
        </p>
        <%= raw post.description %>
    </div>
<% end %>
<br>

<%= link "← All posts", to: Routes.blog_path(@conn, :index) %>

lib/nimble_school_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>NimbleSchool</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>